# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LearnObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'ReactiveObjC'

  target 'LearnObjCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnObjCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
